name: mapbox_gl_web
description: Web platform implementation of mapbox_gl
version: 0.16.0
homepage: https://github.com/tobrun/flutter-mapbox-gl

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/noroshii-main/maps.git
      path: mapbox_gl_platform_interface
  # mapbox_gl_language_dart も mapbox_gl_dartに依存していて、依存解決に失敗するらしい
  # なんとかしたい
  # mapbox_gl_dart:
  #   git:
  #     url: https://github.com/noroshii-main/mapbox-gl-dart.git
  #     ref: master
  mapbox_gl_language_dart:
    git:
      url: https://github.com/noroshii-main/mapbox-gl-language-dart.git
      ref: main
  image: ">=3.0.0 <5.0.0"

dependency_overrides:
  mapbox_gl_platform_interface:
    path: ../mapbox_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

  flutter: ">=2.0.0"
